export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_START = "SIGNUP_USER_START";
export const SIGNUP_USER_ERROR = "SIGNUP_USER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const GET_USER_PROCESS = "GET_USER_PROCESS";
export const GET_USER_PROCESS_START = "GET_USER_PROCESS_START";
export const GET_USER_PROCESS_ERROR = "GET_USER_PROCESS_ERROR";

export const CREATE_PROCESS = "CREATE_PROCESS";
export const CREATE_PROCESS_START = "CREATE_PROCESS_START";
export const CREATE_PROCESS_ERROR = "CREATE_PROCESS_ERROR";

export const EDIT_PROCESS = "EDIT_PROCESS";
export const EDIT_PROCESS_START = "EDIT_PROCESS_START";
export const EDIT_PROCESS_ERROR = "EDIT_PROCESS_ERROR";

export const DELETE_PROCESS = "DELETE_PROCESS";
export const DELETE_PROCESS_START = "DELETE_PROCESS_START";
export const DELETE_PROCESS_ERROR = "DELETE_PROCESS_ERROR";

export const CREATE_TASK = "CREATE_TASK";
export const CREATE_TASK_START = "CREATE_TASK_START";
export const CREATE_TASK_ERROR = "CREATE_TASK_ERROR";

export const EDIT_TASK = "EDIT_TASK";
export const EDIT_TASK_START = "EDIT_TASK_START";
export const EDIT_TASK_ERROR = "EDIT_TASK_ERROR";

export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_START = "DELETE_TASK_START";
export const DELETE_TASK_ERROR = "DELETE_TASK_ERROR";
